### PR TITLE
Convert Windows newline to Linux newline

### PR DESCRIPTION
**Pull request by kkimdev**
The content is identical other than newline change.

### CODE REVIEW

**Comment by suj97** [comment]
What exactly does this do?

**Comment by kkimdev** [comment]
It doesn't do anything... FYI: http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

**Comment by suj97** [comment]
The travis build isn't passing on the commit.

**Comment by kkimdev** [comment]
We don't have `.travis.yml` file in this repo yet.

**Pull request merged**
